### PR TITLE
Current network adapter

### LINKED ISSUE #101: Validate a minimum password length for a wireless network
**Describe the bug**

When you configure a wireless network using **NetworkSettings.SetupWirelessNetwork**, you can set a password of any length, but if you set a password with a length less than 8 characters then the wpa_supplicant service cannot use the value, generating errors that are hard to track.

In order to avoid these errors, the password length, if one is provided, is required to have at less 8 characters.

### LINKED ISSUE #102: Include a funtion to obtain the current network adapter in use.
Include a function to obtain the current network adapter in use. This could be accomplished by parsing the results of the **route** command:

```
$ route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
192.168.1.0     *               255.255.255.0   U     1      0        0 eth0
link-local      *               255.255.0.0     U     1000   0        0 eth0
default         192.168.1.1     0.0.0.0         UG    0      0        0 eth0
```

The _Iface_ column in the line with destination _default_ tells you which interface is used.

[Reference](https://unix.stackexchange.com/questions/14961/how-to-find-out-which-interface-am-i-using-for-connecting-to-the-internet)

### PR DESCRIPTION
**Pull request by Serk352**
**GetCurrentAdapterName** was added in NetworkSettings class, also, **NetworkSettings.SetupWirelessNetwork** was refactored to ensure that the password has at least a length of 8 characters.

Fix #101 . 
Fix #102 .

### CODE REVIEW

File: src/Unosquare.RaspberryIO/Computer/NetworkSettings.cs [hunk 1]
```diff
@@ -98,16 +98,17 @@ public async Task<List<WirelessNetworkInfo>> RetrieveWirelessNetworks(string[] a
...
         /// <param name="networkSsid">The network ssid.</param>
-        /// <param name="password">The password.</param>
+        /// <param name="password">The password (8 characters as minimum, if not, will be ignored).</param>
         /// <param name="countryCode">The 2-letter country code in uppercase. Default is US.</param>
         /// <returns>True if successful. Otherwise, false.</returns>
         public async Task<bool> SetupWirelessNetwork(string adapterName, string networkSsid, string password = null, string countryCode = "US")
         {
             // TODO: Get the country where the device is located to set 'country' param in payload var
             var payload = $"country={countryCode}\nctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev\nupdate_config=1\n";
+            var networkPassword = password.Length >= 8 ? password : null;
```
Comment (k3z0) [inline src/Unosquare.RaspberryIO/Computer/NetworkSettings.cs]: Throw Exception

File: src/Unosquare.RaspberryIO/Computer/NetworkSettings.cs [hunk 2]
```diff
@@ -98,13 +98,17 @@ public async Task<List<WirelessNetworkInfo>> RetrieveWirelessNetworks(string[] a
...
-        /// <param name="password">The password.</param>
+        /// <param name="password">The password (8 characters as minimum length).</param>
         /// <param name="countryCode">The 2-letter country code in uppercase. Default is US.</param>
         /// <returns>True if successful. Otherwise, false.</returns>
         public async Task<bool> SetupWirelessNetwork(string adapterName, string networkSsid, string password = null, string countryCode = "US")
         {
             // TODO: Get the country where the device is located to set 'country' param in payload var
             var payload = $"country={countryCode}\nctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev\nupdate_config=1\n";
+
+            if (password != null && password.Length < 8)
```
Comment (k3z0) [inline src/Unosquare.RaspberryIO/Computer/NetworkSettings.cs]:
```suggestion
            if (!string.IsNullOrWhiteSpace(password) && password.Length < 8)
            
```

File: src/Unosquare.RaspberryIO/Computer/NetworkSettings.cs [hunk 3]
```diff
@@ -98,13 +98,17 @@ public async Task<List<WirelessNetworkInfo>> RetrieveWirelessNetworks(string[] a
...
+                throw new InvalidOperationException("The password length should be at least 8 characters long");
```
Comment (k3z0) [inline src/Unosquare.RaspberryIO/Computer/NetworkSettings.cs]:
```suggestion
                throw new InvalidOperationException("The password must be at least 8 characters length.");
```
